services:
  backend:
    build:
      context: ./server
    container_name: flotteq-backend
    ports:
      - "9093:5000"
    volumes:
      - ./server/uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_HOST=flotteq-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=flotteq
    depends_on:
      - flotteq-db

  frontend-tenant:
    build:
      context: ./frontend/tenant
    container_name: flotteq-frontend-tenant
    ports:
      - "9092:80"
    depends_on:
      - backend

  frontend-internal:
    build:
      context: ./frontend/internal
    container_name: flotteq-frontend-internal
    ports:
      - "9091:80"
    depends_on:
      - backend

  flotteq-db:
    image: postgres:15
    container_name: flotteq-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flotteq

  ia-assistant:
    image: ollama/ollama:latest
    container_name: flotteq-ia
    ports:
      - "11435:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped

volumes:
  db-data:
  ollama-data:

